<a href="https://colab.research.google.com/github/Hwarriach/Data-Processing/blob/main/Data_Processing_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
import pandas as pd
import random

In [38]:
# Generate an array of zeroes using inbuilt numpy function.
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# Run the given code and find the dot product of both arrays.

a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)


[[6 7 7 2]
 [5 6 6 3]
 [2 2 9 5]]
[[7 3 7]
 [9 4 9]
 [7 9 2]
 [2 5 3]]


In [40]:
a.dot(b)

array([[158, 119, 125],
       [137, 108, 110],
       [105, 120,  65]])

In [41]:
np.dot(a,b)

array([[158, 119, 125],
       [137, 108, 110],
       [105, 120,  65]])

In [42]:
# Read the csv file provided using pandas and display the first 5 entries

data = pd.read_csv('data.csv')
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [43]:
# Describe the data with all features.

data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


In [45]:
# Find the total count of missing values for each feature.

data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [46]:
# Display all the unique values from the 'DESCRIPTION’ column.

data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [47]:
# Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

data.groupby('DESCRIPTION')['OBJECTID', 'UNIT_NAME', 'ACRES', 'SHAPE.AREA', 'SHAPE.LEN'].mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [48]:
# Generate a random sample of 10 rows from the data.

data.sample(n = 10)

OBJECTID                                   UNIT_NAME  \
6         27                   Lake Metigoshe State Park   
5         26                        Icelandic State Park   
2         23             Fort Abraham Lincoln State Park   
0         21                   Fort Stevenson State Park   
18        39             Gunlogson State Nature Preserve   
15        34                   Lake Sakakawea State Park   
20        41           Missouri River State Natural Area   
11        32                      Sully Creek State Park   
19        40  Head of the Mountain State Nature Preserve   
4         25                   Grahams Island State Park   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
6              State Park  1508.53    0.000751   0.212196  
5              State Park   930.30    0.000461   0.166712  
2              State Park   836.47    0.000399   0.119868  
0              State Park   586.48    0.000284   0.135641  
18  State Nature Preserve    95.89    0.000048   0.040465  
15             State Park   739.52    0.000357   0.191806  
20     State Natural Area   174.39    0.000083   0.087192  
11             State Park    63.03    0.000030   0.024016  
19  State Nature Preserve    72.30    0.000034   0.033885  
4              State Park   959.33    0.000469   0.125546

In [49]:
# Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

data['New_feature'] = random.random()
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.099853  
1              State Park   273.16    0.000129   0.080067     0.099853  
2              State Park   836.47    0.000399   0.119868     0.099853  
3              State Park   933.78    0.000444   0.128733     0.099853  
4              State Park   959.33    0.000469   0.125546     0.099853  
5              State Park   930.30    0.000461   0.166712     0.099853  
6              State Park  1508.53    0.000751   0.212196     0.099853  
7              State Park   524.81    0.000256   0.130420     0.099853  
8     Interpretive Center    14.71    0.000007   0.016774     0.099853  
9   State Recreation Area    11.40    0.000005   0.009396     0.099853  
10             State Park  6492.93    0.003136   0.313756     0.099853  
11             State Park    63.03    0.000030   0.024016     0.099853  
12  State Recreation Area    51.23    0.000025   0.022095     0.099853  
13  State Recreation Area   247.11    0.000120   0.050518     0.099853  
14             State Park   775.28    0.000378   0.145220     0.099853  
15             State Park   739.52    0.000357   0.191806     0.099853  
16     State Natural Area   264.84    0.000127   0.067082     0.099853  
17  State Recreation Area    21.56    0.000010   0.013294     0.099853  
18  State Nature Preserve    95.89    0.000048   0.040465     0.099853  
19  State Nature Preserve    72.30    0.000034   0.033885     0.099853  
20     State Natural Area   174.39    0.000083   0.087192     0.099853  
21  State Recreation Area  1236.98    0.000615   0.338800     0.099853  
22  State Recreation Area   695.04    0.000345   0.086487     0.099853  
23             State Park   569.07    0.000274   0.180257     0.099853  
24  State Recreation Area    25.22    0.000013   0.026357     0.099853

In [50]:
# Replace zero value of column 'OBJECTID' with mean value permanently.

data[data["OBJECTID"]==0]=data['OBJECTID'].mean()

In [51]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.099853  
1   0.080067     0.099853  
2   0.119868     0.099853  
3   0.128733     0.099853  
4   0.125546     0.099853